INSERT INTO TB_PRODUTO (CATEGORIA, NOME,  DESCRICAO, VALOR) VALUES ('INFORMATICA', 'Notebook Acer', 'Acer Aspire 3 • Processador Intel® Core™ i3 – 1005G1 – 10° Geração', 1000);
INSERT INTO TB_PRODUTO (CATEGORIA, NOME,  DESCRICAO, VALOR) VALUES ('INFORMATICA', 'Cartucho HP', 'Cartucho HP 664 Preto Original ', 50.0);
INSERT INTO TB_PRODUTO (CATEGORIA, NOME,  DESCRICAO, VALOR) VALUES ('ELETRONICO', 'Lavadora de Roupas', 'Lavadora de Roupas Electrolux 11Kg LES11 Essencial Care Branca - 110V', 1708.59);

INSERT INTO TB_CUPOM (CODIGO, DESCRICAO, DESCONTO) VALUES ('LOJ101', 'Loja 01', 10);
INSERT INTO TB_CUPOM (CODIGO, DESCRICAO, DESCONTO) VALUES ('INT516', 'Instagram', 5);

INSERT INTO TB_CARRINHO (DESCONTO_COMPRA, DESCONTO_CUPOM, DESCONTO_ITEM, SUB_TOTAL_COMPRA, SUB_TOTAL_ITEM, TOTAL_COMPRA, TOTAL_ITEM) VALUES (0,0,0,0,0,0,0);